---
title: Setting up a Personal Blog with Blogdown, Academic, and Netlify
author: Stephan Kadauke
date: '2019-10-28'
slug: setting-up-a-personal-blog-with-blogdown-academic-and-netlify
categories: []
tags: []
subtitle: 'First post!'
summary: 'This blog post describes (mainly for my future self) how I set up this blog.'
authors: []
lastmod: '2019-10-28T19:57:56-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

What could be more **meta** than writing my first blog post about setting up my blog?

## Set up Blogdown

The first step was to create the site as described in [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/). 

To install the latest version of blogdown, I ran the following:

```{r eval=FALSE}
install.packages("devtools")
devtools::install_github("rstudio/blogdown")
blogdown::install_hugo()
```

I decided on the [Academic](https://github.com/gcushen/hugo-academic) theme, created a new project named `cellsgenesanddata`, and started writing this post using the `New Post` add-in.

## Continuous Deployment

Continuous deployment using [Netlify](https://www.netlify.com) and [GitHub](https://www.github.com) is an awesome workflow since it enforces version control, and whenever I push a change to my GitHub account, Netlify will automatically update and publish my website.

Here are the steps I followed:

1. On GitHub, create a new public repository named `cellsgenesanddata`. 
2. Tell RStudio that I want this project under version control with `git`: **Tools** → **Project Options** → **Git/SVN** → **Git**.
3. Commit all files and add the remote repository:

```{bash, eval = FALSE}
git add -A
git commit -m "First commit"
git remote add origin https://github.com/skadauke/cellsgenesanddata
git push -u origin master
```

4. On Netlify, create a new site from Git. Note that the default Hugo version Netlify will use is too old, so we need to add an environment variable. **New site from Git** → **GitHub** → **Only select repositories** → `skadauke/cellsgenesanddata` → **Advanced Settings** → **New variable ** → `HUGO_VERSION` = `0.59.0` → **Deploy site**.


## Configuration

There are a couple of files I don't want to add to the repository. The `public/` folder holds the rendered page, which is not necessary since Netlify renders its own version. Also, it is poor form to share your operating system’s cache files.

Here are the contents of my `.gitignore` file:

```{}
.Rproj.user
.Rhistory
.RData
.Ruserdata

/public

# OS files
.DS_Store
.Spotlight-V100
.Trashes
Thumbs.db
```

### Netlify

I changed the site name to <https://cellsgenesanddata.netlify.com>.

### Academic

Source: <https://sourcethemes.com/academic/docs/get-started/>

In the `config.toml` file, I changed the following: 

```{toml}
title = "Cells, Genes, and Data"
baseurl = "https://cellsgenesanddata.netlify.com/"
```

The `content/home` folder contains **widgets** that are to be displayed on the homepage. We will want the following widgets to be active and inactive all others by setting `active = false` in the `.md` file. It's possible to position the widgets by modifying the `weight` parameter:

- `about.md`
- `posts.md`
- `projects.md`
- `talks.md`
- `contact.md`

The `config/_default/params.toml` file controls the behavior of the Academic theme. I edited the **Contact Details** section to read:

```{toml}
email = "skadauke@gmail.com"
phone = ""

contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/StephanKadauke"},
  ]
```

The `about.md` widget gets its content from `content/authors/admin/_index.md`. I edited this file extensively. I also added a square cropped photo under the name `content/authors/admin/avatar.png`. 

The contents of the navigation menu can be modified in the `config/_default/menu.toml` file. I edited this to show the elements on the home page and added a downloadable PDF of my CV. 

Finally, I deleted unused example pages.

